name = "epitomestudio"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = [
  # Enable Node.js API
  "nodejs_compat",
  # Allow to fetch URLs in your app
  "global_fetch_strictly_public"
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "epitomestudio"

[images]
# Enable image optimization
binding = "IMAGES"

# Optional: Uncomment to enable R2 caching for Next.js ISR
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "<BUCKET_NAME>"
